server {
    listen 80;
    server_name bananemauve.com www.bananemauve.com;

    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Gestion des fichiers PHP via PHP-FPM
    location ~ \.php$ {
        fastcgi_pass php:9000;          # Nom du service PHP-FPM dans docker-compose
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        include fastcgi_params;
    }

    # Erreurs 404
    error_page 404 /404.html;
    location = /40x.html { }

    # Erreurs serveur
    error_page 500 502 503 504 /50x.html;
    location = /50x.html { }
}
